---
title: "Homework 2 Machine Learning"
output: html_document
date: "2022-10-07"
---
```{r}
mydata<-read.csv("~/downloads/UniversalBank.csv")
```

```{r}
summary(mydata)
```

```{r}
str(mydata)
```



```{r}
mydata<-subset(mydata, select=-c(ID, ZIP.Code))
```

```{r}
mydata<-read.csv("~/downloads/UniversalBank.csv")
q<-class2ind(as.factor(mydata$Education))
colnames(q)<- c('Education_1','Education_2','Education_3')
mydata2<-cbind(mydata[,1:7],q,mydata[,9:14])
```

```{r}
norm_model<-preProcess(mydata2,method = c("range"))
mydata_normalized<-predict(norm_model,mydata2)
```

```{r}
mydata_normalized<-mydata_normalized[,-2]
index_train<-createDataPartition(mydata_normalized$Income,p=0.6, list = FALSE)
train<-mydata_normalized[index_train,]
test<-mydata_normalized[-index_train,]
```

```{r}
set.seed(2019)
Train_Index<-createDataPartition(mydata1$Education, p= 0.6 , list=FALSE)
Train_Data<-mydata1[Train_Index,]  #3001 observations
Validation_Data<-mydata1[-Train_Index,] #1999 observations
```

```{r}
Test_Data <- data.frame(Age=40 , Experience=10, Income = 84, Family = 2, CCAvg = 2, Education_1 = 0, Education_2 = 1, Education_3 = 0, Mortgage = 0, Securities.Account = 0, CD.Account = 0, Online = 1,  CreditCard = 1, stringsAsFactors = FALSE)
```

```{r}
train.norm.df    <- Train_Data
valid.norm.df    <- Validation_Data
test.norm.df     <- Test_Data
maindata.norm.df <- mydata1
head(maindata.norm.df)
```

```{r}
# use preProcess() from the caret package to normalize .
norm.values <- preProcess(Train_Data[,-7], method=c("center", "scale"))
train.norm.df[,-7] <- predict(norm.values, Train_Data[,-7])  #Training Data
valid.norm.df [,-7]<- predict(norm.values, Validation_Data[,-7])#Validation Data
test.norm.df <- predict(norm.values, Test_Data)#Test Data
maindata.norm.df[,-7] <- predict(norm.values,UBank_data[,-7]) #Training + Validation data
head(maindata.norm.df)
```
```{r}
#library(FNN)
set.seed(2019)
prediction <- knn(train = train.norm.df[,-7], test = valid.norm.df[,-7], 
          cl = train.norm.df[,7], k = 1, prob=TRUE) 
actual= valid.norm.df$Personal.Loan
prediction_prob = attr(prediction,"prob")
table(prediction,actual)  
mean(prediction==actual)  
```

```{r}
#library(class)
NROW(train.norm.df)
sqrt(3001)
```
```{r}
#library(caret)
#library(FNN)
accuracy.df <- data.frame(k = seq(1, 60, 1), accuracy = rep(0, 60))
# compute knn for different k on validation.
for(i in 1:60) {
prediction <- knn(train = train.norm.df[,-7], test = valid.norm.df[-7], 
          cl = train.norm.df[,7], k = i, prob=TRUE) 
accuracy.df[i,2] <- mean(prediction==actual)
}
accuracy.df  
```
```{r}
#library(FNN)
set.seed(2019)
prediction <- knn(train = train.norm.df[,-7], test = valid.norm.df[,-7], 
          cl = train.norm.df[,7], k = 3, prob=TRUE) 
actual= valid.norm.df$Personal.Loan
prediction_prob = attr(prediction,"prob")
#Answer 3: confusion matrix for the best k value =3
table(prediction,actual)  
#accuracy of the best k=3
mean(prediction==actual)  
```

```{r}
#library(FNN)
prediction_test <- knn(train = maindata.norm.df[,-7], test = Test_Data, 
          cl = maindata.norm.df[,7], k = 1, prob=TRUE) 
head(prediction_test)
```
```{r}

set.seed(2019)
Test_Index_1 = createDataPartition(mydata1$Age, p= 0.2 , list=FALSE) 
Test_Data_1  = mydata1 [Test_Index_1,]
Rem_DATA = mydata1[-Test_Index_1,] 
Train_Index_1 = createDataPartition(Rem_DATA$Age, p= 0.5 , list=FALSE)
Train_Data_1 = Rem_DATA[Train_Index_1,] #Training data
Validation_Data_1 = Rem_DATA[-Train_Index_1,] #Validation data
```

```{r}
#Data Normalization
# Copy the original data
train.norm.df_1 <- Train_Data_1
valid.norm.df_1 <- Validation_Data_1
test.norm.df_1 <- Test_Data_1
rem_data.norm.df_1 <- Rem_DATA
norm.values_1 <- preProcess(Train_Data_1[-7], method=c("center", "scale"))
train.norm.df_1[-7] <- predict(norm.values_1, Train_Data_1[-7])  #Training Data
valid.norm.df_1[-7] <- predict(norm.values_1, Validation_Data_1[-7])#Validation Data
test.norm.df_1[-7] <- predict(norm.values_1, test.norm.df_1[-7]) #Test Data
test.norm.df_1[-7] <- predict(norm.values_1, Test_Data_1[-7])
rem_data.norm.df_1[-7] <- predict(norm.values_1,Rem_DATA[-7]) #Training + Validation data
head(test.norm.df_1)
```
```{r}
#library(FNN)
set.seed(2019)
prediction_Q5 <- knn(train = train.norm.df_1[,-7], test = valid.norm.df_1[,-7], 
          cl = train.norm.df_1[,7], k = 3, prob=TRUE) 
actual= valid.norm.df_1$Personal.Loan
prediction_prob = attr(prediction_Q5,"prob")
table(prediction_Q5,actual)  #confusion matrix for the best k value =3
mean(prediction_Q5==actual)  #accuracy of the best k=3
```

```{r}
library(FNN)
set.seed(2019)
prediction_Q5 <- knn(train = rem_data.norm.df_1[,-7], test = test.norm.df_1[,-7], 
          cl = rem_data.norm.df_1[,7], k = 3, prob=TRUE) 
actual= test.norm.df_1$Personal.Loan
prediction_prob = attr(prediction_Q5,"prob")
table(prediction_Q5,actual) 
mean(prediction_Q5==actual) 
```